### GET notes/:id
GET http://localhost:4000/api/notes/606df871bb4afd2f9814f143

### GET notes
GET http://localhost:4000/api/notes

### POST Creating a new note
POST http://localhost:4000/api/notes
Content-Type: application/json

{
   "title": "COMER",
    "content": "Tengo que comer",
    "author": "606df7ba51775605d89c5ee0",
    "date": 1613620442237
}


### PUT Update note

PUT http://localhost:4000/api/notes/602deaed5671352c8c6d9d7e
Content-Type: application/json

{
    "title": "COMER",
    "content": "Tengo que comer joder",
    "author": "606df7ba51775605d89c5ee0",
    "date": 1613620442237
}

### DELETE Delete note
DELETE http://localhost:4000/api/notes/606df821bb4afd2f9814f142